DROP TABLE PERSONAJE CASCADE CONSTRAINTS;
DROP TABLE ESPECIE CASCADE CONSTRAINTS;
DROP TABLE PLANETA CASCADE CONSTRAINTS;
DROP TABLE VEHICULO CASCADE CONSTRAINTS;
DROP TABLE OBJETO CASCADE CONSTRAINTS;
DROP TABLE EVENTO CASCADE CONSTRAINTS;
DROP TABLE FACCION CASCADE CONSTRAINTS;
DROP TABLE RANGO CASCADE CONSTRAINTS;
DROP TABLE HABILIDAD CASCADE CONSTRAINTS;
DROP TABLE BATALLA CASCADE CONSTRAINTS;
DROP TABLE DROIDE CASCADE CONSTRAINTS;
DROP TABLE HOLOCRON CASCADE CONSTRAINTS;
DROP TABLE ORDEN CASCADE CONSTRAINTS;
DROP TABLE CRIATURA CASCADE CONSTRAINTS;
DROP TABLE RELIGION CASCADE CONSTRAINTS;


CREATE TABLE PLANETA ( 
    ID_PLANETA INT PRIMARY KEY,
    NOMBRE VARCHAR2(255) UNIQUE NOT NULL,
    REGION VARCHAR2(255),
    CLIMA VARCHAR2(255),
    POBLACION INT
);

CREATE TABLE ESPECIE ( 
    ID_ESPECIE INT PRIMARY KEY,
    NOMBRE VARCHAR2(255) UNIQUE NOT NULL,
    CLASIFICACION VARCHAR2(255),
    ID_PLANETA_ORIGEN INT,
    FOREIGN KEY (ID_PLANETA_ORIGEN) REFERENCES PLANETA(ID_PLANETA) ON DELETE SET NULL 
);

CREATE TABLE FACCION ( 
    ID_FACCION INT PRIMARY KEY,
    NOMBRE VARCHAR2(255) UNIQUE NOT NULL,
    LIDER VARCHAR2(255),
    IDEOLOGIA VARCHAR2(255)
);

CREATE TABLE RANGO ( 
    ID_RANGO INT PRIMARY KEY,
    NOMBRE VARCHAR2(255) UNIQUE NOT NULL,
    ID_FACCION INT,
    FOREIGN KEY (ID_FACCION) REFERENCES FACCION(ID_FACCION) ON DELETE CASCADE
);


CREATE TABLE PERSONAJE ( 
    ID_PERSONAJE INT PRIMARY KEY,
    NOMBRE VARCHAR2(255) UNIQUE NOT NULL,
    ID_ESPECIE INT,
    ID_PLANETA_ORIGEN INT,
    ID_FACCION INT,
    ID_RANGO INT,
    ID_ORDEN INT,
    ID_RELIGION INT,
    FOREIGN KEY (ID_ESPECIE) REFERENCES ESPECIE(ID_ESPECIE) ON DELETE SET NULL,
    FOREIGN KEY (ID_PLANETA_ORIGEN) REFERENCES PLANETA(ID_PLANETA) ON DELETE SET NULL,
    FOREIGN KEY (ID_FACCION) REFERENCES FACCION(ID_FACCION) ON DELETE SET NULL,
    FOREIGN KEY (ID_RANGO) REFERENCES RANGO(ID_RANGO) ON DELETE SET NULL,
    FOREIGN KEY (ID_ORDEN) REFERENCES ORDEN(ID_ORDEN) ON DELETE SET NULL,
    FOREIGN KEY (ID_RELIGION) REFERENCES RELIGION(ID_RELIGION) ON DELETE SET NULL
);

CREATE TABLE VEHICULO ( 
    ID_VEHICULO INT PRIMARY KEY,
    NOMBRE VARCHAR2(255) UNIQUE NOT NULL,
    TIPO VARCHAR2(255),
    FABRICANTE VARCHAR2(255),
    ID_PERSONAJE INT,
    FOREIGN KEY (ID_PERSONAJE) REFERENCES PERSONAJE(ID_PERSONAJE) ON DELETE SET NULL
);

CREATE TABLE HABILIDAD( 
    ID_HABILIDAD INT PRIMARY KEY,
    NOMBRE VARCHAR2(255) UNIQUE NOT NULL,
    TIPO VARCHAR2(255)
);

CREATE TABLE EVENTO ( 
    ID_EVENTO INT PRIMARY KEY,
    NOMBRE VARCHAR2(255) UNIQUE NOT NULL,
    LUGAR VARCHAR2(255),
    FECHA DATE
);

CREATE TABLE BATALLA ( 
    ID_BATALLA INT PRIMARY KEY,
    NOMBRE VARCHAR2(255) UNIQUE NOT NULL,
    LUGAR VARCHAR2(255),
    FECHA DATE,
    FACCION_GANADORA INT,
    FOREIGN KEY (FACCION_GANADORA) REFERENCES FACCION(ID_FACCION) ON DELETE SET NULL
);

CREATE TABLE DROIDE ( 
    ID_DROIDE INT PRIMARY KEY,
    NOMBRE VARCHAR2(255) UNIQUE NOT NULL,
    MODELO VARCHAR2(255),
    FABRICANTE VARCHAR2(255),
    ID_FACCION INT,
    FOREIGN KEY (ID_FACCION) REFERENCES FACCION(ID_FACCION) ON DELETE SET NULL
);

CREATE TABLE ORDEN (
    ID_ORDEN INT PRIMARY KEY,
    NOMBRE VARCHAR2(255) UNIQUE NOT NULL,
    IDEOLOGIA VARCHAR2(255),
    AFILICACION VARCHAR2(255) CHECK (AFILICACION IN ('JEDI', 'SITH', 'NEUTRO', 'DESCONOCIDO'))
);

CREATE TABLE CRIATURA ( 
    ID_CRIATURA INT PRIMARY KEY,
    NOMBRE VARCHAR2(255) UNIQUE NOT NULL,
    ESPECIE VARCHAR2(255),
    HABITAT VARCHAR2(255),
    ID_PLANETA INT,
    FOREIGN KEY (ID_PLANETA) REFERENCES PLANETA(ID_PLANETA) ON DELETE SET NULL
);

CREATE TABLE RELIGION ( 
    ID_RELIGION INT PRIMARY KEY,
    NOMBRE VARCHAR2(255) UNIQUE NOT NULL,
    DEIDAD_O_FILOSOFIA VARCHAR2(255)
);

CREATE TABLE HOLOCRON ( 
    ID_HOLOCRON INT PRIMARY KEY,
    NOMBRE VARCHAR2(255) UNIQUE NOT NULL,
    TIPO VARCHAR2(255) CHECK (TIPO IN ('JEDI', 'SITH')),
    CREADOR VARCHAR2(255),
    ID_PERSONAJE INT,
    FOREIGN KEY (ID_PERSONAJE) REFERENCES PERSONAJE(ID_PERSONAJE) ON DELETE SET NULL
);