DROP TABLE PERSONAJE CASCADE CONSTRAINTS; --
DROP TABLE ESPECIE CASCADE CONSTRAINTS; --
DROP TABLE PLANETA CASCADE CONSTRAINTS; --
DROP TABLE NAVE CASCADE CONSTRAINTS; --
DROP TABLE ORGANIZACION CASCADE CONSTRAINTS; --
DROP TABLE ARMA CASCADE CONSTRAINTS; --
DROP TABLE EVENTO CASCADE CONSTRAINTS; --
DROP TABLE HABILIDAD CASCADE CONSTRAINTS; --
DROP TABLE OBJETO CASCADE CONSTRAINTS; --
DROP TABLE DROIDE CASCADE CONSTRAINTS; --
DROP TABLE SECTOR_GALACTICO CASCADE CONSTRAINTS; --
DROP TABLE CLASE_DE_NAVE CASCADE CONSTRAINTS; --
DROP TABLE LENGUAJE CASCADE CONSTRAINTS; --
DROP TABLE RAZA CASCADE CONSTRAINTS; --
DROP TABLE MATERIAL CASCADE CONSTRAINTS; --

CREATE TABLE PERSONAJE (
    PERSONAJE VARCHAR2(100) PRIMARY KEY,
    ESPECIE VARCHAR2(50) NOT NULL,
    PLANETA_DE_ORIGEN VARCHAR2(50) NOT NULL,
    AFILIACION VARCHAR2(100) NOT NULL,
    RANGO VARCHAR2(50) CHECK (RANGO IN ('Maestro', 'Aprendiz', 'General', 'Soldado', 'Lord', 'Emperador')),
    GENERO VARCHAR2(20) CHECK (GENERO IN ('Masculino', 'Femenino', 'Otro', 'No especificado')),
    EDAD NUMBER CHECK (EDAD >= 0),
    FUERZA NUMBER CHECK (FUERZA BETWEEN 0 AND 10),
    ALIADOS VARCHAR2(255),
    ENEMIGOS VARCHAR2(255),
    FECHA_DE_NACIMIENTO VARCHAR(20),
    ESTADO VARCHAR(20) CHECK (ESTADO IN('Vivo', 'Muerto', 'Desconocido')),

    FOREIGN KEY (ESPECIE) REFERENCES ESPECIE(ESPECIE),
    FOREIGN KEY (PLANETA_DE_ORIGEN) REFERENCES PLANETA(PLANETA),
    FOREIGN KEY (AFILIACION) REFERENCES ORGANIZACION(ORGANIZACION)
);

CREATE TABLE ESPECIE (
    ESPECIE VARCHAR2(50) PRIMARY KEY,
    DESCRIPCION VARCHAR2(255),
    PROMEDIO_VIDA NUMBER
);

CREATE TABLE PLANETA (
    PLANETA VARCHAR2(50) PRIMARY KEY,
    DESCRIPCION VARCHAR2(255),
    CLIMA VARCHAR2(50),
    POBLACION NUMBER,
    UBICACION VARCHAR2(100),
    TIPO VARCHAR2(50),

    FOREIGN KEY (UBICACION) REFERENCES SECTOR_GALACTICO(SECTOR)
);

CREATE TABLE NAVE (
    NAVE VARCHAR2(50) PRIMARY KEY,
    DESCRIPCION VARCHAR2(255),
    CLASE VARCHAR2(50),
    CAPACIDAD NUMBER,
    ARMAMENTO VARCHAR2(255),
    VELOCIDAD NUMBER,
    TRIPULACION NUMBER,

    FOREIGN KEY (CLASE) REFERENCES CLASE_DE_NAVE(CLASE)
);

CREATE TABLE ORGANIZACION (
    ORGANIZACION VARCHAR2(100) PRIMARY KEY,
    DESCRIPCION VARCHAR2(255),
    TIPO VARCHAR2(50) CHECK (TIPO IN('Gubernamental', 'Militar', 'Religiosa', 'Criminal', 'Comercial', 'Neutra')),
    FUNDACION VARCHAR2(50),
    BASE_OPERACION VARCHAR2(100)
);

CREATE TABLE ARMA (
    ARMA VARCHAR2(100) PRIMARY KEY,
    TIPO VARCHAR2(50) CHECK (TIPO IN ('Blaster', 'Sable de luz', 'Torpedo', 'Cañón', 'Lanza', 'Dardo')),
    DESCRIPCION VARCHAR2(255),
    POTENCIA NUMBER,
    ALCANCE NUMBER,
    FABRICANTE VARCHAR2(100)
);

CREATE TABLE EVENTO (
    EVENTO VARCHAR2(255) PRIMARY KEY,
    DESCRIPCION VARCHAR2(100),
    FECHA VARCHAR2(50),
    UBICACION VARCHAR2(100),
    IMPACTO VARCHAR2(255),
    PARTICIPANTES VARCHAR2(255)
);

CREATE TABLE HABILIDAD (
    HABILIDAD VARCHAR2(255) PRIMARY KEY,
    DESCRIPCION VARCHAR2(255),
    TIPO VARCHAR2(50) CHECK(TIPO IN ('Fuerza', 'Combate', 'Tecnología', 'Tácticas', 'Diplomacia', 'Mente')),
    NIVEL NUMBER,
    REQUISITOS VARCHAR2(255)
);

CREATE TABLE OBJETO (
    OBJETO VARCHAR2(100) PRIMARY KEY,
    DESCRIPCION VARCHAR2(255),
    TIPO VARCHAR2(50) CHECK(TIPO IN('Tecnológico', 'Religioso', 'Artefacto', 'Antiguo', 'Arma')),
    VALOR NUMBER,
    PROPIETARIO VARCHAR2(100),
    FECHA_DESCUBRIMIENTO VARCHAR2(50)
);

CREATE TABLE DROIDE (
    DROIDE VARCHAR2(100) PRIMARY KEY,
    TIPO VARCHAR2(50) CHECK (TIPO IN ('Astromecánico', 'Protocolar', 'Médico', 'De combate', 'De mantenimiento')),
    MODELO VARCHAR2(50),
    FABRICANTE VARCHAR2(100),
    DESCRIPCION VARCHAR2(255),
    PROPIETARIO VARCHAR2(100),
    FECHA_CREACION VARCHAR2(20),

    FOREIGN KEY (PROPIETARIO) REFERENCES PERSONAJE(PERSONAJE)
);

CREATE TABLE SECTOR_GALACTICO (
    SECTOR VARCHAR2(100) PRIMARY KEY,
    DESCRIPCION VARCHAR2(255),
    COORDENADAS VARCHAR2(100),
    NUMERO_PLANETAS NUMBER,
    GOBERNADOR VARCHAR2(100)

);

CREATE TABLE CLASE_DE_NAVE (
    CLASE VARCHAR2(50) PRIMARY KEY,
    DESCRIPCION VARCHAR2(255),
    CAPACIDAD_MAX NUMBER,
    VELOCIDAD_MAX NUMBER,
    ARMAMENTO VARCHAR2(255)
);

CREATE TABLE LENGUAJE (
    LENGUAJE VARCHAR2(50) PRIMARY KEY,
    DESCRIPCION VARCHAR2(255),
    ORIGEN VARCHAR2(100),
    HABLANTES NUMBER,
    ESCRITO VARCHAR(10) CHECK (ESCRITO IN ('True', 'False'))
);

CREATE TABLE RAZA (
    RAZA VARCHAR2(100) PRIMARY KEY,
    DESCRIPCION VARCHAR2(255),
    PLANETA_ORIGEN VARCHAR2(50),
    ESPERANZA_VIDA NUMBER,

    FOREIGN KEY (PLANETA_ORIGEN) REFERENCES PLANETA(PLANETA)
);

CREATE TABLE MATERIAL (
    MATERIAL VARCHAR2(100) PRIMARY KEY,
    DESCRIPCION VARCHAR2(255),
    PROPIEDADES VARCHAR2(255),
    USOS VARCHAR2(255),
    RAREZA VARCHAR2(50) CHECK (RAREZA IN ('Común', 'Poco común', 'Raro', 'Muy raro'))
);